[plugin]
repository = "https://github.com/MeiHasCrashed/OhHey.git"
commit = "252fcb8da1db2f4f499d419a5d790ceedda945a5"
owners = ["MeiHasCrashed"]
project_path = "src/OhHey/"
changelog = "Initial testing release."